### ISSUE TITLE
Error when clicking on "Refresh dbt_ catalog"

### ISSUE THREAD

**Issue by b-per** [ciejer/tangata_local#31]
Hi,

When I click on "Refresh dbt_ catalog", the following error appears in the console.
FYI, I am running tangata in WSL, in a conda virtual env where I have both dbt and tangata installed.

```
reloading dbt_...
sh: 1: cd: can't cd to . 
complete
512
dbt_ update failed.
```

**Comment by ciejer** [comment]
Seems to be WSL (perhaps unix-based) -specific.
A previous version of the app allowed setting dbt folder via command line flags; now the app assumes the folder you're in is your dbt folder so the cd is no longer needed anyway.
Should be fixed in 0.1.9.
