### ISSUE TITLE
Feature - Use existing yml file in folder instead of schema.yml

### ISSUE THREAD

**Issue by b-per** [ciejer/tangata_local#35]
In my dbt project, I like to list my tables/column descriptions and tests in a file called `<current_folder>.yml`. For example, in my marts folder, the file is called `marts.yml` and not `schema.yml`. I find it much easier when looking for `yml` files for all of them to have different names rather than having many `schema.yml` in different folders.

If I have already added info about a specific table, tangata, finds the correct `yml` file and add the new info in the correct place. But if for a model in the same folder (e.g. `marts`), I add info about a table that is not in my existing `yml` file, it adds it to a new `schema.yml` file. Ideally, I'd like this info to be added to any other existing `yml` file in the current folder rather than creating a new one.

**Comment by ciejer** [comment]
Interesting.  
You may have noticed I removed the `config` panel in the latest release as all the config options were relating the multiuser nodeJS version of the app. I'd be keen to readd the panel, with this as the first setting.  
Config would be stored in a `/tangata.yaml` file at project root - along with any other settings that should be shared with the repository code (separate from the newly created #40 which would be user-specific) 

Do you see any downsides with this storage approach?

**Comment by b-per** [comment]
I think it would make sense to store config that way.

What might be a bit more complex is implementing the logic of how to find the `yml` file name. We are following this approach https://discourse.getdbt.com/t/how-we-structure-our-dbt-projects/355 , which means that for the staging layers, the name of the `yml` is not just the name of the folder but `stg_<folder_name>`.

So the logic could be, if there is just 1 existing `yml` file in the same folder with some table/column def and/or tests (there might be cases where 1- the folder has a different `yml` file with just the sources definition or 2- multiple `yml` files have been created for the descriptions/tests ), use this one, otherwise, use `schema.yml`.

**Comment by ciejer** [comment]
Added in 0.1.14 - config page now re-enabled, with 3 options for yml storage.
