### ISSUE TITLE
Feature - Add the ability to mention if a test is supposed to be an error test or a warn one

### ISSUE THREAD

**Issue by b-per** [ciejer/tangata_local#36]
Currently, all new tests will raise errors when failing. 

It would be great if tangata was giving the ability to define the severity of the tests, making some of them return warnings rather than errors: https://docs.getdbt.com/reference/resource-properties/tests#severity

**Comment by ciejer** [comment]
The rendering was there, was leaving editing for a later day... now there's a dropdown menu to change them. Releasing in 0.1.14
