### ISSUE TITLE
Use `preserve_quotes = True` in ruamel.yaml

### ISSUE THREAD

**Issue by b-per** [ciejer/tangata_local#48]
Would it be possible to add `preserve_quotes = True` or make it possible to configure the value in the configuration? More info on the flag here: 
https://stackoverflow.com/questions/39262556/preserve-quotes-and-also-add-data-with-quotes-in-ruamel

In my case, without this flag the first changes to `dbt_project.yml` modifies all the lines about source-paths, macro-paths etc... removing the quotes. Not a big deal but the git history just becomes less clean that way.

**Comment by ciejer** [comment]
Done in 0.1.18
